### ISSUE TITLE
Error "Item has already been added. Key in dictionary: 'Path' Key being added:"  when using VS plugin

### ISSUE THREAD

**Issue by kblunde** [OpenCppCoverage/OpenCppCoveragePlugin#8] opened 2017-10-11 09:17 UTC
Hello,
Thanks for a great tool!
I have used you tool for some time in Visual Studio with success.
However, after upgrading my machine to Windows 10 I get the following error using the plugin:

`

Start building ..\ElementModelGoogleTest\ElementModelGoogleTest.vcxproj Debug|x86
Start computing code coverage...
C:\Users\kblu\Source\Repos\ElementModel2\Build\Debug\ElementModelGoogleTest.exe has binary type: SCS_32BIT_BINARY
Run:
"C:\Users\kblu\AppData\Local\Microsoft\VisualStudio\15.0_e9dddeb9\Extensions\i31a3fnq.5ql\OpenCppCoverage-x86\OpenCppCoverage.exe" --export_type "binary:c:\users\kblu\AppData\Local\Temp\2bsa4nqo.n4c" --sources "C:\Users\kblu\Source\Repos\ElementModel2\Build\packages\gmock.1.7.0\lib\native\src\gmock" --sources "C:\Users\kblu\Source\Repos\ElementModel2\Build\packages\gmock.1.7.0\lib\native\src\gtest" --sources "C:\Users\kblu\Source\Repos\ElementModel2\ElementModelGoogleTest" --sources "C:\Users\kblu\Source\Repos\ElementModel2\ElementModelLibrary" --modules "C:\Users\kblu\Source\Repos\ElementModel2\Build\Debug\ElementModelGoogleTest.exe" --modules "C:\Users\kblu\Source\Repos\ElementModel2\Build\Debug\ElementModelLibrary.lib" --working_dir "C:\Users\kblu\Source\Repos\ElementModel2\ElementModelGoogleTest\\"  --plugin  -- "C:\Users\kblu\Source\Repos\ElementModel2\Build\Debug\ElementModelGoogleTest.exe" 
**System.ArgumentException: Item has already been added. Key in dictionary: 'Path'  Key being added: 'PATH'
   at OpenCppCoverage.VSPackage.CoverageRunner.<>c__DisplayClass12_0.<<OnCoverageFinishedAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenCppCoverage.VSPackage.ErrorHandler.<ExecuteAsync>d__5.MoveNext()**
`

I have tried different projects, VS2015, VS2017, 32bit and 64 bit. The problem is there in all cases. Running opencppcoverage from the command line works fine.

**Comment by OpenCppCoverage** [comment] 2017-10-16 20:10
Hello,

In your Visual Studio project settings, in Debugging tab, there is the field "Environment".
This field allows to override the environment variables.
It seems in your project, you override PATH which already exists and so this creates the problem.

The issue is fixed by [this commit](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/commit/f1bbecec4ad45fcc77210a7ada9df731a1f0d452)

I hope it will help,

OpenCppCoverage

**Comment by crazyzlj** [comment] 2017-12-04 06:11
Hi,
I intend to use OpenCppCoveragePlugin in VS2013 and have the same problem. Since the bug has been fixed, could you please update the release version ASAP?
Thank you very much.

**Comment by OpenCppCoverage** [comment] 2017-12-04 21:10
Hello,

I suggest compiling the master branch.
Please let me know if you have any issue with the [build instructions](https://github.com/OpenCppCoverage/OpenCppCoveragePlugin).

OpenCppCoverage

**Comment by OpenCppCoverage** [comment] 2018-02-08 18:38
Hello,

Fixed in the latest version: https://github.com/OpenCppCoverage/OpenCppCoveragePlugin/releases/tag/0.9.4.2

OpenCppCoverage.

**Closed** 2018-02-08 18:38 UTC
